### ISSUE TITLE
getObject returning empty strings instead of nil for absent values

### ISSUE THREAD

**Issue by cbreden** [softlayer/softlayer-ruby#49]
I noticed the getObject behavior changed a bit with the XMLRPC calls.  Key without values used to return `nil` but are now returning as empty strings like `""`.  There are a few cases where we had to alter logic to account for this.

Was this an intended change?  I know the use of nil always tends to be a hot topic.

**Comment by renier** [comment]
This is due to Ruby's xmlrpc library. Maybe it changed with newer versions of Ruby, but currently [it will parse an empty string node as an empty string](https://github.com/ruby/xmlrpc/blob/master/lib/xmlrpc/parser.rb#L232-L242).

And an empty string node it gets from the API:
`<value><string/></value>`
instead of omitting the field.

So this should be either fixed-enabled in the xmlrpc library or the server, but I don't see this as a bug in softlayer-ruby. Please reopen if you disagree.

P.S. There is a `blank?` method added to _Object_ by the _activesupport_ gem that will check for both nil and empty string values: e.g.`is object.notes.blank?`, which would be very convenient in this case.
